server:
  port: 8001

spring:
  application:
    name: cloud-Payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/dianzi?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: root
    druid:
      validation-query: select 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dianzi.springcloud.entities