server:
  port: 8003

spring:
  application:
    name: cloud-provider-payment
  datasource:
    url: jdbc:mysql://localhost:3306/dianzi?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: root
    druid:
      validation-query: select 1


  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.dianzi.springcloud.entities
  cloud:
    zookeeper:
      connect-string: 192.168.7.180:2181