server:
  port: 8004

spring:
  application:
    name: consul-provider-payment
  datasource:
    url: jdbc:mysql://localhost:3306/dianzi?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: root
    druid:
      validation-query: select 1
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
      host: 192.168.7.180
      port: 8500