server:
  port: 80
spring:
  application:
    name: cloud-comsumer-feign-hystrix-order-service
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

hystrix:
  command:
    default:
      execution:
        timeout:
          enable: false
feign:
  hystrix:
    enabled: true
